### ISSUE TITLE
Extra Data in Response

### ISSUE THREAD

**Issue by coler-j** [Pylons/pyramid_openapi3#211]
For response validation, why are extra properties allowed? Is there a way to add validation to this?

I.e. 

Schema:

```
    Thing:
      type: object
      properties:
        id:
          type: "integer"
```

Response:

```
{
   id: 1,
   fieldThatNotInSchema: "dirp"
}
```

I would expect this response to fail validation, but it does not.
